theme: jekyll-theme-cayman
description: "Machine Learning Efficiency Workshop, <br/> Friday August 26, <br/>Deep Learning Indaba 2022.  Tunisia"
basepath: "mledge2022/"
google_analytics: UA-156425047-1

navigation:
  - text: HOME
    url: /
  - text: CALL FOR SPOTLIGHT TALKS
    url: /cfp.html
  - text: SCHEDULE
    url: /schedule.html
    layout: post
  - text: DATES
    url: /dates.html
    layout: project

  # - text: PAPERS
  #   url: /papers.html
  #   layout: post
  # - text: INSTRUCTIONS
  #   url: /instructions.html
  # - text: VIRTUAL
  #   url: /virtual.html
  - text: ORGANIZERS
    url: /organizers.html
